## 4-е домашнее задание - Библиотека numpy

Подпишите этот блокнот: укажите ФИО и номер группы. Выполненное задание загрузите в свой репозиторий «<b>Spring2023Python</b>» в github в папку "<b>homework04</b>".  

Перед выполнением этого домашнего задания полезно прочитать про возможности и основные методы библиотеки numpy:  
http://acm.mipt.ru/twiki/bin/view/Cintro/PythonNumpy  


1.	Создайте равномерное разбиение интервала от -1.3 до 2.5 на 64 отрезка.

In [1]:
import numpy as np
np.linspace(-1.3, 2.5, 65)

array([-1.3     , -1.240625, -1.18125 , -1.121875, -1.0625  , -1.003125,
       -0.94375 , -0.884375, -0.825   , -0.765625, -0.70625 , -0.646875,
       -0.5875  , -0.528125, -0.46875 , -0.409375, -0.35    , -0.290625,
       -0.23125 , -0.171875, -0.1125  , -0.053125,  0.00625 ,  0.065625,
        0.125   ,  0.184375,  0.24375 ,  0.303125,  0.3625  ,  0.421875,
        0.48125 ,  0.540625,  0.6     ,  0.659375,  0.71875 ,  0.778125,
        0.8375  ,  0.896875,  0.95625 ,  1.015625,  1.075   ,  1.134375,
        1.19375 ,  1.253125,  1.3125  ,  1.371875,  1.43125 ,  1.490625,
        1.55    ,  1.609375,  1.66875 ,  1.728125,  1.7875  ,  1.846875,
        1.90625 ,  1.965625,  2.025   ,  2.084375,  2.14375 ,  2.203125,
        2.2625  ,  2.321875,  2.38125 ,  2.440625,  2.5     ])

2.	Сгенерируйте numpy массив длины $3n$, заполненный циклически числами 1, 2, 3, 1, 2, 3, 1....

In [2]:
n = int(input('Введите n:'))
tmp = []
i = 1
while n:
    tmp.append(i)
    i += 1
    if i == 4:
        i = 1
    n -= 1
a = np.array(tmp)
a

Введите n: 400


array([1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1,
       2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2,
       3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3,
       1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1,
       2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2,
       3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3,
       1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1,
       2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2,
       3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3,
       1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1,
       2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2,
       3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3,
       1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1,
       2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1,

3.	Создайте массив первых 10 нечетных целых чисел.

In [3]:
np.arange(1, 20, 2)

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

4.  Создайте массив нулей размера 10 x 10, а затем создайте в нём "рамку" из единиц по краям.

In [4]:
a = np.zeros((10, 10), int)
a[0, :] = np.ones(10)
a[9, :] = np.ones(10)
a[:, 0] = np.ones(10)
a[:, 9] = np.ones(10)
a

array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])

5.  Создайте массив 8 x 8 с шахматной доской из нулей и единиц.

In [5]:
a = np.zeros((8, 8), int)
for i in range(-6, 8, 2):
    a += np.eye(8, 8, i, int)
a

array([[1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1]])

6.  Создайте функцию, которая создает $n×n$ матрицу с $(i,j)$-элементом, равным $i+j$.

In [ ]:
def nxn(n):
    a = np.arange(n)
    b = a.copy()
    a = a[:, np.newaxis]
    return a + b

n = int(input('n = '))
nxn(n)

n =  14


array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13],
       [ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14],
       [ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15],
       [ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16],
       [ 4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17],
       [ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18],
       [ 6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [ 7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20],
       [ 8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21],
       [ 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23],
       [11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24],
       [12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25],
       [13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26]])

7. Примените функцию dot для перемножения вектор на вектор, матрицу на вектор и матрицу на матрицу.

In [ ]:
a = np.arange(10, 45, 7)
b = np.linspace(10, 40, 5)

print(np.dot(b, -b), np.dot(a,b), np.dot(a - 10, a * 100))

-3687.5 3525.0 217000


8. Вычислите cos(x) и sin(x) на интервале [0,1] с шагом $0.05$, а затем объедините оба массива чисел как строки в один массив.

In [ ]:
arrcos = np.cos(np.arange(0, 1, 0.05))
arrsin = np.sin(np.arange(0, 1, 0.05))
res = list(arrcos) + list(arrsin)
res

[1.0,
 0.9987502603949663,
 0.9950041652780258,
 0.9887710779360422,
 0.9800665778412416,
 0.9689124217106447,
 0.955336489125606,
 0.9393727128473789,
 0.9210609940028851,
 0.9004471023526769,
 0.8775825618903728,
 0.8525245220595057,
 0.8253356149096782,
 0.7960837985490559,
 0.7648421872844884,
 0.7316888688738209,
 0.6967067093471654,
 0.6599831458849821,
 0.6216099682706644,
 0.5816830894638835,
 0.0,
 0.04997916927067833,
 0.09983341664682815,
 0.14943813247359924,
 0.19866933079506122,
 0.24740395925452294,
 0.2955202066613396,
 0.3428978074554514,
 0.3894183423086505,
 0.43496553411123023,
 0.479425538604203,
 0.5226872289306592,
 0.5646424733950355,
 0.6051864057360395,
 0.6442176872376911,
 0.6816387600233341,
 0.7173560908995228,
 0.7512804051402927,
 0.7833269096274834,
 0.8134155047893737]

9. Создайте матрицу $A$ размера $3×5$ из случайных чисел с равномерным распределением на отрезке $[-1,3]$ (используйте np.random.rand)

In [ ]:
A = np.random.rand(3, 5) * 4 - 1
A

array([[-0.84297679,  1.95026727, -0.03622694, -0.72513512, -0.90772779],
       [ 2.57578484,  0.73929454, -0.6982964 ,  2.41232135,  1.11248571],
       [ 1.75526988,  0.47930856,  0.01300771,  2.93030525, -0.12767952]])

10. Найдите сумму всех элементов, сумму внутри строк, сумму внутри столбцов, а также среднее значение, дисперсию и стандартное отклонение чисел для каждой строки матрицы $A$. (Подобно тому, как sorted имеет необязательный аргумент key=, многие функции Numpy имеют необязательный аргумент axis=)


In [ ]:
s_general = np.sum(A)
s_columns = np.sum(A, axis=0)
s_rows = np.sum(A, axis=1)
means = np.mean(A, axis=1)
dispetrions = np.var(A, axis=1)
devs = np.std(A, axis=1)

print(f'Сумма: {s_general};\nСумма по строкам: {s_columns};\nСумма внутри столбцов: {s_rows};\n')
print(f'Среднее значение строк: {means}\nДисперсия: {dispetrions}\nСтандартное отклонение: {devs}')

Сумма: 10.630002543583432;
Сумма по строкам: [ 3.48807792  3.16887038 -0.72151564  4.61749147  0.07707841];
Сумма внутри столбцов: [-0.56179937  6.14159004  5.05021187];

Среднее значение строк: [-0.11235987  1.22831801  1.01004237]
Дисперсия: [1.16042634 1.43638698 1.36258823]
Стандартное отклонение: [1.07723087 1.19849363 1.16729955]


11.  Отнимите от каждого элемента матрицы $A$ среднее по строке и поделите на стандартное отклонение строки.

In [ ]:
A -= means[:, np.newaxis]
A /= devs[:, np.newaxis]
A

array([[-0.67823615,  1.9147494 ,  0.07067467, -0.56884301, -0.7383449 ],
       [ 1.12430037, -0.40803176, -1.60752995,  0.98790958, -0.09664823],
       [ 0.63842011, -0.45466805, -0.8541378 ,  1.64504722, -0.97466147]])

12. Отсортируйте матрицу $A$ по 3-ому столбцу, т.е. поменяйте местами строки матрицы так, чтобы 3-й столбец оказался отсортированным. Используйте для этого slicing + argsort + indexing.

In [ ]:
i = np.argsort(A[:, 2])
print(i)
A = np.stack((A[i[0], :], A[i[1], :], A[i[2], :]), axis=0)
A

[1 2 0]


array([[ 1.12430037, -0.40803176, -1.60752995,  0.98790958, -0.09664823],
       [ 0.63842011, -0.45466805, -0.8541378 ,  1.64504722, -0.97466147],
       [-0.67823615,  1.9147494 ,  0.07067467, -0.56884301, -0.7383449 ]])

13. Посчитайте две матрицы: $B = A^TA$ и $C = AA^T$. Что вы можете о них сказать? Какого они размера? В чём их сходство и отличие?

In [ ]:
B = np.dot(A.T, A)
C = np.dot(A, A.T)
print(B, C, sep='\n\n')

print('\nСходство в том, что обе матрицы квадратные. Различия – в размерности, потому что А прямоугольная')

[[ 2.13163583 -2.04767175 -2.40057938  2.54674822 -0.23013292]
 [-2.04767175  4.03947821  1.17959672 -2.24024071 -0.93116247]
 [-2.40057938  1.17959672  3.31869884 -3.03339404  0.93567786]
 [ 2.54674822 -2.24024071 -3.03339404  4.00572806 -1.27884153]
 [-0.23013292 -0.93116247  0.93567786 -1.27884153  1.50445906]]

[[ 5.          3.99570428 -2.1480371 ]
 [ 3.99570428  5.         -1.58007817]
 [-2.1480371  -1.58007817  5.        ]]

Сходство в том, что обе матрицы квадратные. Различия – в размерности, потому что А прямоугольная


14. Найдите сумму диагональных элементов матриц $B$ и $C$.

In [ ]:
np.sum(np.diagonal(B)) + np.sum(np.diagonal(C))

30.0

15.	Посчитайте детерминант и ранг матриц $A$, $B$ и $C$, посмотрите на спектр (набор собственных значений) матриц $B$ и $C$, какие выводы вы можете сделать?  
(подсказка: используйте готовые функции из библиотеки np.linalg). 


In [ ]:
print(np.linalg.matrix_rank(A))
print(np.linalg.det(B), np.linalg.matrix_rank(B))
print(np.linalg.det(C), np.linalg.matrix_rank(C))
print(np.linalg.eig(B)[0], np.linalg.eig(C)[0])

3
1.2297939539407025e-31 3
36.74155676609421 3
[ 1.03089848e+01  3.73740322e+00  9.53611982e-01 -3.51599725e-16
  4.98759085e-16] [10.3089848   0.95361198  3.73740322]


**Вывод:** ранг матриц В и С равен рангу матрицы А, детерминанты В и С – разные

16. Численно посчитать определённый интеграл  3-мя методами:  
a)	Прямоугольников $\int\limits_a^b {f(x)dx \approx \Delta x\sum\limits_{k = 0}^N {f({x_k})} }$  
b)	Трапеций $\int\limits_a^b {f(x)dx \approx \frac{{\Delta x}}{2}\left( {f({x_0}) + 2\sum\limits_{k = 1}^{N - 1} {f({x_k})}  + f({x_N})} \right)}$  
c)	По правилу Симпсона  $\int\limits_a^b {f(x)dx \approx \frac{{\Delta x}}{3}\left( {f({x_0}) + 2\sum\limits_{k = 1}^{N/2 - 1} {f({x_{2k}})}  + 4\sum\limits_{k = 1}^{N/2} {f({x_{2k - 1}})}  + f({x_N})} \right)}$  


В реализации этих методов цикл for для суммирования использовать нельзя.  
Нужно посчитать значение интеграла с некоторым шагом интегрирования (например начать с 0.1), потом уменьшить его в десять раз и ещё раз посчитать и так до тех пор пока отличие в ответах будет в 5-м знаке после запятой, т.е. чтобы ошибка была меньше 1e-5. Получить ответы для 3-х разных методов и сделать соответствующие выводы.  

Далее необходимо сравнить полученные оценки с аналитическим решением (т.е. формульным, которое вы должны сами посчитать на листочке и вбить формулу-ответ).   

В качестве интеграла взять два из следующих примеров:  
- один с номером, сгенерированным случайным образом с помощью функции np.random.randint(9), в качестве seed для генератора случайных чисел взять номер своего студенческого билета. 
- второй номер - под номером 9, несобственный интерграл. Подумайте, как сделать подбор шага интегрирования адаптивным.

<table width="80%"
       align="center">
    <tr>
        <td> 0) $\int\limits_3^4 {\frac{{{x^2} + 3}}{{x - 2}}dx}$ </td>
        <td> 1) $\int\limits_{ - 2}^{ - 1} {\frac{{x + 1}}{{{x^3} - {x^2}}}dx}$ </td>
        <td> 2) $\int\limits_1^2 {\frac{{{e^{1/{x^2}}}}}{{{x^3}}}dx}$ </td>
        <td> 3) $\int\limits_1^e {\frac{{\cos (\ln x)}}{x}dx}$ </td>
        <td> 4) $\int\limits_1^e {\frac{{dx}}{{x(1 + {{\ln }^2}x)}}}$ </td>
    </tr>                
    <tr>
        <td> 5) $\int\limits_0^{\pi /2} {{{\cos }^3}\alpha \;d\alpha }$ </td>
        <td> 6) $\int\limits_0^{1/3} {c{h^2}3x\;dx}$ </td>
        <td> 7) $\int\limits_2^3 {\frac{{dy}}{{{y^2} - 2y - 8}}dy}$ </td>
        <td> 8) $\int\limits_0^2 {\frac{{2x - 1}}{{2x + 1}}dx}$ </td>
        <td> 9) $\int\limits_{3/4}^2 {\frac{{dx}}{{\sqrt {2 + 3x - 2{x^2}} }}}$ </td>
        </tr>
</table>

In [ ]:
np.random.seed(1032201719)
np.random.randint(9)

5

In [20]:
def compute_integral(f, a, b, tolerance, method):
    
    tol = np.Inf
    n = 10
    I0, I1 = 0, 0
    while tol > tolerance:
        fakeb = (b - a) * 0.9 + a
        dx = (fakeb - a) / n
        if b - fakeb < tolerance * 0.01:
            return 0
        #print(a, fakeb, b)
        xx = np.arange(a, fakeb, dx)
        yy = f(xx)
        
        if method == 'rect':
            I1 = yy.sum() * dx
        elif method == 'trap':
            I1 = (yy[0] + 2 * yy[1 : -1].sum() + yy[-1]) * dx / 2
        elif method == 'Simpson':
            I1 = (yy[0] + 2 * yy[2 : -1 : 2].sum() + 4 * yy[1 : -1 : 2].sum() + yy[-1]) * dx / 3
            
        I1 += compute_integral(f, fakeb, b, 10 ** -5, method)
        
        tol = abs(I1 - I0)
        I0 = I1
        #print(xx)
        #print(I1, I0, tol)
        #print(n)
        n *= 10
        
    return I1
    
def f(x):
    return np.cos(x) ** 3

def f1(x):
    return np.sqrt(2 + 3 * x - 2 * x ** 2) ** -1

print('Первый интеграл: ', compute_integral(f, 0, np.pi/2, 10 ** -5, 'rect'), compute_integral(f, 0, np.pi/2, 10 ** -5, 'trap'), compute_integral(f, 0, np.pi/2, 10 ** -5, 'Simpson'))
print('Второй интеграл: ', compute_integral(f1, 0.75, 2., 10 ** -5, 'rect'), compute_integral(f1, 0.75, 2, 10 ** -5, 'trap'), compute_integral(f1, 0.75, 2, 10 ** -5, 'Simpson'))

Первый интеграл:  0.6666676441246575 0.6666661303855737 0.6666659346525999
Второй интеграл:  1.1104021765183707 1.1104025839534102 1.1104019427161946


**Выводы:** точность решения возрастает с применением более сложных методов.
Это можно заметить, если знать аналитические решения для интегралов, но у меня осталось буквально пять минут на коммит, так что я не успею показать это в код