## 4-е домашнее задание - Библиотека numpy

Подпишите этот блокнот: укажите ФИО и номер группы. Выполненное задание загрузите в свой репозиторий «<b>Spring2023Python</b>» в github в папку "<b>homework04</b>".  

Перед выполнением этого домашнего задания полезно прочитать про возможности и основные методы библиотеки numpy:  
http://acm.mipt.ru/twiki/bin/view/Cintro/PythonNumpy  


1.	Создайте равномерное разбиение интервала от -1.3 до 2.5 на 64 отрезка.

In [1]:
import numpy as np
np.linspace(-1.3, 2.5, 65)

array([-1.3     , -1.240625, -1.18125 , -1.121875, -1.0625  , -1.003125,
       -0.94375 , -0.884375, -0.825   , -0.765625, -0.70625 , -0.646875,
       -0.5875  , -0.528125, -0.46875 , -0.409375, -0.35    , -0.290625,
       -0.23125 , -0.171875, -0.1125  , -0.053125,  0.00625 ,  0.065625,
        0.125   ,  0.184375,  0.24375 ,  0.303125,  0.3625  ,  0.421875,
        0.48125 ,  0.540625,  0.6     ,  0.659375,  0.71875 ,  0.778125,
        0.8375  ,  0.896875,  0.95625 ,  1.015625,  1.075   ,  1.134375,
        1.19375 ,  1.253125,  1.3125  ,  1.371875,  1.43125 ,  1.490625,
        1.55    ,  1.609375,  1.66875 ,  1.728125,  1.7875  ,  1.846875,
        1.90625 ,  1.965625,  2.025   ,  2.084375,  2.14375 ,  2.203125,
        2.2625  ,  2.321875,  2.38125 ,  2.440625,  2.5     ])

2.	Сгенерируйте numpy массив длины $3n$, заполненный циклически числами 1, 2, 3, 1, 2, 3, 1....

In [2]:
n = int(input('Введите n:'))
tmp = []
i = 1
while n:
    tmp.append(i)
    i += 1
    if i == 4:
        i = 1
    n -= 1
a = np.array(tmp)
a

Введите n: 77


array([1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1,
       2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2,
       3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3,
       1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2])

3.	Создайте массив первых 10 нечетных целых чисел.

In [3]:
np.arange(1, 20, 2)

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

4.  Создайте массив нулей размера 10 x 10, а затем создайте в нём "рамку" из единиц по краям.

In [4]:
a = np.zeros((10, 10), int)
a[0, :] = np.ones(10)
a[9, :] = np.ones(10)
a[:, 0] = np.ones(10)
a[:, 9] = np.ones(10)
a

array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])

5.  Создайте массив 8 x 8 с шахматной доской из нулей и единиц.

In [5]:
a = np.zeros((8, 8), int)
for i in range(-6, 8, 2):
    a += np.eye(8, 8, i, int)
a

array([[1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1]])

6.  Создайте функцию, которая создает $n×n$ матрицу с $(i,j)$-элементом, равным $i+j$.

In [6]:
def nxn(n):
    a = np.arange(n)
    b = a.copy()
    a = a[:, np.newaxis]
    return a + b

n = int(input('n = '))
nxn(n)

n =  10


array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
       [ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [ 4,  5,  6,  7,  8,  9, 10, 11, 12, 13],
       [ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14],
       [ 6,  7,  8,  9, 10, 11, 12, 13, 14, 15],
       [ 7,  8,  9, 10, 11, 12, 13, 14, 15, 16],
       [ 8,  9, 10, 11, 12, 13, 14, 15, 16, 17],
       [ 9, 10, 11, 12, 13, 14, 15, 16, 17, 18]])

7. Примените функцию dot для перемножения вектор на вектор, матрицу на вектор и матрицу на матрицу.

In [7]:
a = np.arange(10, 45, 7)
b = np.linspace(10, 40, 5)

print(np.dot(b, -b), np.dot(a,b), np.dot(a - 10, a * 100))

-3687.5 3525.0 217000


8. Вычислите cos(x) и sin(x) на интервале [0,1] с шагом $0.05$, а затем объедините оба массива чисел как строки в один массив.

In [8]:
arrcos = np.cos(np.arange(0, 1, 0.05))
arrsin = np.sin(np.arange(0, 1, 0.05))
res = list(arrcos) + list(arrsin)
res

[1.0,
 0.9987502603949663,
 0.9950041652780258,
 0.9887710779360422,
 0.9800665778412416,
 0.9689124217106447,
 0.955336489125606,
 0.9393727128473789,
 0.9210609940028851,
 0.9004471023526769,
 0.8775825618903728,
 0.8525245220595057,
 0.8253356149096782,
 0.7960837985490559,
 0.7648421872844884,
 0.7316888688738209,
 0.6967067093471654,
 0.6599831458849821,
 0.6216099682706644,
 0.5816830894638835,
 0.0,
 0.04997916927067833,
 0.09983341664682815,
 0.14943813247359924,
 0.19866933079506122,
 0.24740395925452294,
 0.2955202066613396,
 0.3428978074554514,
 0.3894183423086505,
 0.43496553411123023,
 0.479425538604203,
 0.5226872289306592,
 0.5646424733950355,
 0.6051864057360395,
 0.6442176872376911,
 0.6816387600233341,
 0.7173560908995228,
 0.7512804051402927,
 0.7833269096274834,
 0.8134155047893737]

9. Создайте матрицу $A$ размера $3×5$ из случайных чисел с равномерным распределением на отрезке $[-1,3]$ (используйте np.random.rand)

In [9]:
A = np.random.rand(3, 5) * 4 - 1
A

array([[ 0.48098755,  1.80972324,  0.94988515, -0.55708931,  2.32471916],
       [-0.91080136,  2.16030497,  1.49948002, -0.54971896,  1.25801854],
       [ 1.9588103 ,  1.18207975,  0.36138984,  2.34475857,  2.04062169]])

10. Найдите сумму всех элементов, сумму внутри строк, сумму внутри столбцов, а также среднее значение, дисперсию и стандартное отклонение чисел для каждой строки матрицы $A$. (Подобно тому, как sorted имеет необязательный аргумент key=, многие функции Numpy имеют необязательный аргумент axis=)


In [10]:
s_general = np.sum(A)
s_columns = np.sum(A, axis=0)
s_rows = np.sum(A, axis=1)
means = np.mean(A, axis=1)
dispetrions = np.var(A, axis=1)
devs = np.std(A, axis=1)

print(f'Сумма: {s_general};\nСумма по строкам: {s_columns};\nСумма внутри столбцов: {s_rows};\n')
print(f'Среднее значение строк: {means}\nДисперсия: {dispetrions}\nСтандартное отклонение: {devs}')

Сумма: 16.353169149558457;
Сумма по строкам: [1.52899649 5.15210797 2.81075502 1.23795029 5.62335939];
Сумма внутри столбцов: [5.00822578 3.45728321 7.88766015];

Среднее значение строк: [1.00164516 0.69145664 1.57753203]
Дисперсия: [1.02138632 1.44783143 0.51676921]
Стандартное отклонение: [1.01063659 1.20325867 0.71886661]


11.  Отнимите от каждого элемента матрицы $A$ среднее по строке и поделите на стандартное отклонение строки.

In [11]:
A -= means[:, np.newaxis]
A /= devs[:, np.newaxis]
A

array([[-0.51517787,  0.79957335, -0.05121525, -1.54232934,  1.30914912],
       [-1.33159896,  1.22072532,  0.67152924, -1.03151187,  0.47085628],
       [ 0.53038806, -0.55010522, -1.69174944,  1.06727246,  0.64419414]])

12. Отсортируйте матрицу $A$ по 3-ому столбцу, т.е. поменяйте местами строки матрицы так, чтобы 3-й столбец оказался отсортированным. Используйте для этого slicing + argsort + indexing.

In [12]:
i = np.argsort(A[:, 2])
print(i)
A = np.stack((A[i[0], :], A[i[1], :], A[i[2], :]), axis=0)
A

[2 0 1]


array([[ 0.53038806, -0.55010522, -1.69174944,  1.06727246,  0.64419414],
       [-0.51517787,  0.79957335, -0.05121525, -1.54232934,  1.30914912],
       [-1.33159896,  1.22072532,  0.67152924, -1.03151187,  0.47085628]])

13. Посчитайте две матрицы: $B = A^TA$ и $C = AA^T$. Что вы можете о них сказать? Какого они размера? В чём их сходство и отличие?

In [13]:
B = np.dot(A.T, A)
C = np.dot(A, A.T)
print(B, C, sep='\n\n')

print('\nСходство в том, что обе матрицы квадратные. Различия – в размерности, потому что А прямоугольная')

[[ 2.31987554 -2.32920831 -1.76510638  2.73420266 -0.9597635 ]
 [-2.32920831  2.4321036   1.70944259 -3.07951025  1.26717236]
 [-1.76510638  1.70944259  3.31559068 -2.41925717 -0.84066972]
 [ 2.73420266 -3.07951025 -2.41925717  4.58186704 -1.81730228]
 [-0.9597635   1.26717236 -0.84066972 -1.81730228  2.35056313]]

[[ 5.         -1.42918973 -3.31143214]
 [-1.42918973  5.          3.83502932]
 [-3.31143214  3.83502932  5.        ]]

Сходство в том, что обе матрицы квадратные. Различия – в размерности, потому что А прямоугольная


14. Найдите сумму диагональных элементов матриц $B$ и $C$.

In [14]:
np.sum(np.diagonal(B)) + np.sum(np.diagonal(C))

30.000000000000007

15.	Посчитайте детерминант и ранг матриц $A$, $B$ и $C$, посмотрите на спектр (набор собственных значений) матриц $B$ и $C$, какие выводы вы можете сделать?  
(подсказка: используйте готовые функции из библиотеки np.linalg). 


In [15]:
print(np.linalg.matrix_rank(A))
print(np.linalg.det(B), np.linalg.matrix_rank(B))
print(np.linalg.det(C), np.linalg.matrix_rank(C))
print(np.linalg.eig(B)[0], np.linalg.eig(C)[0])

3
-4.377485329030066e-31 3
22.721736738388486 3
[ 1.08263143e+01  3.58889550e+00  5.84790191e-01 -3.23852729e-16
 -2.61199837e-17] [10.82631431  3.5888955   0.58479019]


**Вывод:** ранг матриц В и С равен рангу матрицы А, детерминанты В и С – разные

16. Численно посчитать определённый интеграл  3-мя методами:  
a)	Прямоугольников $\int\limits_a^b {f(x)dx \approx \Delta x\sum\limits_{k = 0}^N {f({x_k})} }$  
b)	Трапеций $\int\limits_a^b {f(x)dx \approx \frac{{\Delta x}}{2}\left( {f({x_0}) + 2\sum\limits_{k = 1}^{N - 1} {f({x_k})}  + f({x_N})} \right)}$  
c)	По правилу Симпсона  $\int\limits_a^b {f(x)dx \approx \frac{{\Delta x}}{3}\left( {f({x_0}) + 2\sum\limits_{k = 1}^{N/2 - 1} {f({x_{2k}})}  + 4\sum\limits_{k = 1}^{N/2} {f({x_{2k - 1}})}  + f({x_N})} \right)}$  


В реализации этих методов цикл for для суммирования использовать нельзя.  
Нужно посчитать значение интеграла с некоторым шагом интегрирования (например начать с 0.1), потом уменьшить его в десять раз и ещё раз посчитать и так до тех пор пока отличие в ответах будет в 5-м знаке после запятой, т.е. чтобы ошибка была меньше 1e-5. Получить ответы для 3-х разных методов и сделать соответствующие выводы.  

Далее необходимо сравнить полученные оценки с аналитическим решением (т.е. формульным, которое вы должны сами посчитать на листочке и вбить формулу-ответ).   

В качестве интеграла взять два из следующих примеров:  
- один с номером, сгенерированным случайным образом с помощью функции np.random.randint(9), в качестве seed для генератора случайных чисел взять номер своего студенческого билета. 
- второй номер - под номером 9, несобственный интерграл. Подумайте, как сделать подбор шага интегрирования адаптивным.

<table width="80%"
       align="center">
    <tr>
        <td> 0) $\int\limits_3^4 {\frac{{{x^2} + 3}}{{x - 2}}dx}$ </td>
        <td> 1) $\int\limits_{ - 2}^{ - 1} {\frac{{x + 1}}{{{x^3} - {x^2}}}dx}$ </td>
        <td> 2) $\int\limits_1^2 {\frac{{{e^{1/{x^2}}}}}{{{x^3}}}dx}$ </td>
        <td> 3) $\int\limits_1^e {\frac{{\cos (\ln x)}}{x}dx}$ </td>
        <td> 4) $\int\limits_1^e {\frac{{dx}}{{x(1 + {{\ln }^2}x)}}}$ </td>
    </tr>                
    <tr>
        <td> 5) $\int\limits_0^{\pi /2} {{{\cos }^3}\alpha \;d\alpha }$ </td>
        <td> 6) $\int\limits_0^{1/3} {c{h^2}3x\;dx}$ </td>
        <td> 7) $\int\limits_2^3 {\frac{{dy}}{{{y^2} - 2y - 8}}dy}$ </td>
        <td> 8) $\int\limits_0^2 {\frac{{2x - 1}}{{2x + 1}}dx}$ </td>
        <td> 9) $\int\limits_{3/4}^2 {\frac{{dx}}{{\sqrt {2 + 3x - 2{x^2}} }}}$ </td>
        </tr>
</table>

In [16]:
np.random.seed(1032201719)
np.random.randint(9)

5

In [17]:
def compute_integral(f, a, b, tolerance, method):
    """
    Справка:
    (надеюсь, фраза про завышение планки и повышение баллов остальным – шутка)
    
    Аргументы:
    
    f: function
        Функция, которую требуется проинтегрировать
    a, b: integer of real
        Границы интегрирования
    tolerance: integer or real
        Допустимая погрешность
        Интеграл 9 задан так, что мой компьютер не справляется с рассчётами при заданной погрешности больше 1е-3: не хватает памяти.
        Я всё равно уверен в том, что код написан верно, так как при небольших погрешностях всё работает прекрасно.
    method: string
        Метод численного интегрирования
        'rect': метод прямоугольников
        'trap': метод трапеций
        'Simpson': метод Симпсона
        
    Функция сначала разбивает заданный интервал на 10 отрезков, затем вычисляет значение интеграла и погрешность относительно
    предыдущей итерации (начальная погрешность считается бесконечной). Если значение погрешности больше заданной,
    мощность разбиения множества увеличивается в 10 раз, и всё будет повторяться, пока мы не достигнем удовлетворительной погрешности
    
    Пожалуйста, если эта справка хороша, не снижайте ничьи баллы. Я просто очень люблю писать справки, но не хочу задирать планку качества.
    
    """

    tol = np.Inf
    n = 10
    I0, I1 = 0, 0
    while tol > tolerance:
        dx = (b - a) / n
        xx = np.arange(a, b, dx)
        yy = f(xx)
        if method == 'rect':
            I1 = yy.sum() * dx
        elif method == 'trap':
            I1 = (yy[0] + 2 * yy[1 : -1].sum() + yy[-1]) * dx / 2
        elif method == 'Simpson':
            I1 = (yy[0] + 2 * yy[2 : -1 : 2].sum() + 4 * yy[1 : -1 : 2].sum() + yy[-1]) * dx / 3
        tol = abs(I1 - I0)
        I0 = I1
        #print(I1, I0, tol)
        #print(n)
        n *= 10
        
    return I1
    
def f(x):
    return np.cos(x) ** 3

def f1(x):
    return np.sqrt(2 + 3 * x - 2 * x ** 2) ** -1

print('Первый интеграл: ', compute_integral(f, 0, np.pi/2, 10 ** -5, 'rect'), compute_integral(f, 0, np.pi/2, 10 ** -5, 'trap'), compute_integral(f, 0, np.pi/2, 10 ** -5, 'Simpson'))
print('Второй интеграл: ', compute_integral(f1, 0.75, 2, 10 ** -3, 'rect'), compute_integral(f1, 0.75, 2, 10 ** -3, 'trap'), compute_integral(f1, 0.75, 2, 10 ** -3, 'Simpson'))

Первый интеграл:  0.6666674520648301 0.6666666666636734 0.6666666666603757
Второй интеграл:  1.1104901562508713 1.1104110086419872 1.1103638055642207
